version: '2'
services:

  elastic-master-1:
    image: elasticsearch:5.6.4
    container_name: elastic-master-1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - ./conf/elastic-master-1.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9201:9200
    networks:
      - esnet

  elastic-master-2:
    image: elasticsearch:5.6.4
    container_name: elastic-master-2
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - ./conf/elastic-master-2.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9202:9200
    networks:
      - esnet

  elastic-data-1:
    image: elasticsearch:5.6.4
    container_name: elastic-data-1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - ./esdata1:/usr/share/elasticsearch/data
      - ./conf/elastic-data-1.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - esnet

  elastic-data-2:
    image: elasticsearch:5.6.4
    container_name: elastic-data-2
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - ./esdata2:/usr/share/elasticsearch/data
      - ./conf/elastic-data-2.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - esnet

  elastic-data-3:
    image: elasticsearch:5.6.4
    container_name: elastic-data-3
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - ./esdata3:/usr/share/elasticsearch/data
      - ./conf/elastic-data-3.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - esnet

  kibana:
    image: kibana:5.6.4
    container_name: kibana
    ports:
      - 5601:5601
    links:
      - elastic-master-1:elasticsearch
    networks:
      - esnet

networks:
  esnet: