version: '2'
services:

  elastic1:
    image: elasticsearch:5.6.4
    container_name: elastic1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - ./esdata1:/usr/share/elasticsearch/data
      - ./elastic1.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    expose:
      - 9200
    ports:
      - 9200:9200
    networks:
      - esnet

  elastic2:
    image: elasticsearch:5.6.4
    container_name: elastic2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - ./esdata2:/usr/share/elasticsearch/data
      - ./elastic2.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - esnet

  elastic3:
    image: elasticsearch:5.6.4
    container_name: elastic3
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - ./esdata3:/usr/share/elasticsearch/data
      - ./elastic3.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - esnet

  kibana:
    image: kibana:5.6.4
    container_name: kibana
    ports:
      - 5601:5601
    links:
      - elastic1:elasticsearch
    networks:
      - esnet

networks:
  esnet: